sudo: required
services:
  -docker
before_install:
  - docker build -t subrat/client -f ./client/Dockerfile.dev ./client

script:
  - docker run subrat/client npm test -- --coverage

after_success:
  - docker build subrat/client ./client
  - docker build subrat/nginx ./nginx
  - docker build subrat/server ./server
  - docker build subrat/worker ./worker
#docker login 
  - echo "$DOCKER_PASSWORD" | docker login -u "DOCKER_ID" --password-stdin
#push build images to docker hub
  - docker push subrat/client
  - docker push subrat/nginx
  - docker push subrat/server
  - docker push subrat/worker

#
# deploy:
#   provider: elasticbeanstalk
#   region: "ap-south-1"
#   app: "Ndocker"
#   env: "Ndocker-env"
#   bucket_name: "elasticbeanstalk-ap-south-1-155213612701"
#   bucket_path: "Ndocker-demo"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"